name: default
on:
  - push
jobs:
  test:
    strategy:
      matrix:
        go-version:
          - 1.16.x
          - 1.17.x
        os:
          - ubuntu-latest
          - macos-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download mods
        run: go mod download
      - name: Build CLI
        run: go install ./cmd/hof
      - name: Run gen tests
        run: hof test test.cue -s gen -t test
      - name: Run tester tests
        run: hof test test/testers/api/postman.cue
